import { test, expect } from "@playwright/test";
import { login } from "../../lib/login";
import fs from "fs";
const { PNG } = require("pngjs");

test("signoff2", async ({ page }) => {
  await login(page, "mayadav_reconsignoff@ivp.in", "Ivp@123");
  // signoff Reject at first Level
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('Copy of Break_Management_Position');

  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Sign off' }).click();
  await page.locator('#signOffApproveButton').getByRole('button', { name: 'Sign off' }).click();
  await expect(page.locator('#pendingSignOff')).toContainText('Signoff Pending for Approval');
  await page.getByText("QA").click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_16@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_16%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('Copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Reject Sign off' }).click();
  await expect(page.locator('#signOffIcon')).toContainText('Sign off');

  //signoff Reject at second level
  await page.getByRole('button', { name: 'Sign off' }).click();
  await page.locator('#signOffApproveButton').getByRole('button', { name: 'Sign off' }).click();
  await page.getByRole('button', { name: 'Approve Sign off' }).click();
  await expect(page.locator('#pendingSignOff')).toContainText('Signoff Pending for Approval');
  await page.getByRole('button', { name: 'Copy of'}).click();
  await expect(page.locator('#RS_FirstRow')).toContainText('Sign off Status : Pending At Approver Assigned Approver : Operations||SignOff_FirstApprover|Quick_OpsCurrent Approver : OpsHeadSign Off Date :');
  await page.getByTestId('runSatusClose').click();
  await page.getByText("QA").click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_re-arch@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_re-arch%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('Copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Reject Sign off' }).click();
  await expect(page.locator('#signOffIcon')).toContainText('Sign off');

  //signoff reject at Level 3
  await page.getByRole('button', { name: 'Copy of' }).click();
  await expect(page.locator('#RS_FirstRow')).toContainText('Sign off Status : Sign Off Not Intiated');
  await page.getByTestId('runSatusClose').click();
  await page.getByRole('button', { name: 'Sign off' }).click();
  await page.locator('#signOffApproveButton').getByRole('button', { name: 'Sign off' }).click();
  await page.getByRole('button', { name: 'Copy of' }).click();
  await expect(page.locator('#RS_FirstRow')).toContainText('Sign off Status : Pending At Approver Assigned Approver : |OpsHead|SignOff_FirstApprover|Quick_OpsCurrent Approver : Operations');
  await page.getByTestId('runSatusClose').click();
  await page.getByText("QA").click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_16@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_16%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('Copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Approve Sign off' }).click();
  await page.getByText("QA").click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_re-arch@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_re-arch%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('Copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Approve Sign off' }).click();
    await expect(page.locator('#pendingSignOff')).toContainText('Signoff Pending for Approval');
   
  await page.getByText("QA").click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_test_16@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_test_16%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('Copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Reject Sign off' }).click();

  //reject signoff at level 4

  await page.locator('#signOffIcon').click();
  await page.locator('#signOffApproveButton').getByRole('button', { name: 'Sign off' }).click();
  await expect(page.locator('#pendingSignOff')).toContainText('Signoff Pending for Approval');
  await page.getByRole('button', { name: 'Copy of'}).click();
  await expect(page.locator('#RS_FirstRow')).toContainText('Sign off Status : Pending At Approver Assigned Approver : |OpsHead|SignOff_FirstApprover|Quick_OpsCurrent Approver : OperationsSign Off Date :');
  await page.getByTestId('runSatusClose').click();

  await page.getByText("QA").click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_16@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_16%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('Copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Approve Sign off' }).click();
  await page.getByText("QA").click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_re-arch@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_re-arch%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('Copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Approve Sign off' }).click();
    await expect(page.locator('#pendingSignOff')).toContainText('Signoff Pending for Approval');
   
  await page.getByText("QA").click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_test_16@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_test_16%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('Copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Approve Sign off' }).click();
 await expect(page.locator('#pendingSignOff')).toContainText('Signoff Pending for Approval');
   
  await page.getByText("QA").click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_test_re-arch1@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_re-arch1%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@101');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('Copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Approve Sign off' }).click();


//   signoff converted into revoke
//   Revoke rejected at first Level
  await page.getByRole('button', { name: 'Revoke' }).click();
  await page.locator('#signOffApproveButton').getByRole('button', { name: 'Revoke' }).click();
  await page.getByRole('button', { name: 'Copy of' }).click();
  await expect(page.locator('#RS_FirstRow')).toContainText('Sign off Status : Revoke Sign off Pending Assigned Approver : |OpsHead|SignOff_FirstApprover|Quick_OpsCurrent Approver : OperationsSign Off Date :');
  await page.getByTestId('runSatusClose').click();
  await page.getByRole('button', { name: 'Reject Revoke' }).click();
  await expect(page.getByLabel('Error while Signoff Reject')).toContainText('Error while Signoff RejectError while performing Action. Actual Error Message: User does not belong to the Approver Group. Cannot Reject Breaks.');
  await page.getByText('QA').click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_16@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_16%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Reject Revoke' }).click();
  await expect(page.locator('#revokeIcon')).toContainText('Revoke');
  await page.getByRole('button', { name: 'Copy of' }).click();
  await expect(page.locator('#RS_FirstRow')).toContainText('Sign off Status : Signed Off');
  await page.getByTestId('runSatusClose').click();

  // revoke rejected at second Level

  await page.getByRole('button', { name: 'Revoke' }).click();
  await page.locator('#signOffApproveButton').getByRole('button', { name: 'Revoke' }).click();
  await page.getByRole('button', { name: 'Copy of' }).click();
  await expect(page.locator('#RS_FirstRow')).toContainText('Sign off Status : Revoke Sign off Pending Assigned Approver : |OpsHead|SignOff_FirstApprover|Quick_OpsCurrent Approver : OperationsSign Off Date :');
  await page.getByTestId('runSatusClose').click();
  await page.getByText('QA').click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_16@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_16%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Approve Revoke' }).click();
   await page.getByText('QA').click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_re-arch@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_re-arch%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Reject Revoke' }).click();
  //reject revoke at third Level
  await expect(page.locator('#revokeIcon')).toContainText('Revoke');
  await page.getByRole('button', { name: 'Revoke' }).click();
  await page.locator('#signOffApproveButton').getByRole('button', { name: 'Revoke' }).click();
  await page.getByRole('button', { name: 'Copy of' }).click();
  await expect(page.locator('#RS_FirstRow')).toContainText('Sign off Status : Revoke Sign off Pending Assigned Approver : |OpsHead|SignOff_FirstApprover|Quick_OpsCurrent Approver : OperationsSign Off Date :');
    await page.getByTestId('runSatusClose').click();
   await page.getByText('QA').click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_16@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_16%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Approve Revoke' }).click();
   await page.getByText('QA').click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_re-arch@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_re-arch%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Approve Revoke' }).click();

   await page.getByText('QA').click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_test_16@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_test_16%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Reject Revoke' }).click();
   await expect(page.locator('#revokeIcon')).toContainText('Revoke');
   //Reject Revoke at Fourth Level
  await page.getByRole('button', { name: 'Revoke' }).click();
  await page.locator('#signOffApproveButton').getByRole('button', { name: 'Revoke' }).click();
  await page.getByRole('button', { name: 'Copy of', }).click();
  
  await expect(page.locator('#RS_FirstRow')).toContainText('Sign off Status : Revoke Sign off Pending Assigned Approver : |OpsHead|SignOff_FirstApprover|Quick_OpsCurrent Approver : OperationsSign Off Date :')
   await page.getByTestId('runSatusClose').click();
  await page.getByText('QA').click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_16@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_16%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Approve Revoke' }).click();
   await page.getByText('QA').click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_re-arch@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_re-arch%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Approve Revoke' }).click();

   await page.getByText('QA').click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_test_16@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_test_16%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@123');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Approve Revoke' }).click();
  await page.getByText('QA').click();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mayadav_test_re-arch1@ivp.in');
  await page.goto('https://li-reconqaautomation.ivp.in/keycloak/realms/reconqa15autouat/protocol/openid-connect/auth?response_type=code&client_id=rad&redirect_uri=https://li-reconqaautomation.ivp.in/MFRAD/LoginCallback&username=mayadav_re-arch1%40ivp.in');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Ivp@101');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByTestId('menu-icon').click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).click();
  await page.getByRole('textbox', { name: 'Search Text here...' }).fill('copy of Break_Management_Position');
  await page.locator('#btnExpand_1990').click();
  await page.getByRole('textbox', { name: 'Click to view Break Details' }).first().click();
  await page.getByRole('button', { name: 'Reject Revoke' }).click();

  await expect(page.locator('#revokeIcon')).toContainText('Revoke');
  await page.getByRole('button', { name: 'Copy of' }).click();
  await expect(page.locator('#RS_FirstRow')).toContainText('Sign off Status : Signed Off');
  
  await page.getByTestId('runSatusClose').click();





});